// tslint:disable
/**
 * Altana Atlas API
 * Altana Atlas for Regulatory Risk and Trade Compliance
 *
 * OpenAPI spec version: v1.0.142
 * Contact: engineering@altanatech.com
 *
 * NOTE: This file is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the file manually.
 */

export * from "./api";
export * from "./configuration";
